version: '3.8'

services:
  docling-inference:
    build: .
    image: docling-inference:latest
    ports:
      - 8877:8080
    environment:
      - DEV_MODE=0
      - AUTH_TOKEN=dev-key
      - NUM_WORKERS=4  # Optimal for RTX 4090
      - DOCLING_OCR_ENGINE=aws_textract
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./logs:/app/logs
      - hf_cache:/root/.cache/huggingface

volumes:
  hf_cache:
