version: '3.8'

services:
  docling-inference:
    build: .
    image: docling-inference:latest
    ports:
      - 8877:8080
    environment:
      - DEV_MODE=0
      - AUTH_TOKEN=dev-key
      - NUM_WORKERS=4
      - DOCLING_OCR_ENGINE=tesseract
      - TESSERACT_DEVICE=cuda
      - DOCLING_TABLE_EXTRACTION_MODE=tableformer
      - DOCLING_USE_FP16=true
      - BATCH_SIZE=16
      - TORCH_CUDA_ARCH_LIST=8.9
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./logs:/app/logs
      - hf_cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD-SHELL", "nvidia-smi && python /app/check_gpu.py"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hf_cache:
