version: '3.8'

services:
  docling-inference:
    image: docling-inference:latest
    ports:
      - 8877:8080
    environment:
      - DEV_MODE=0
      - AUTH_TOKEN=dev-key
      - NUM_WORKERS=12
    deploy:
      replicas: 1
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: 'gpu'
                value: 1
        limits:
          memory: 16G
    volumes:
      - app_logs:/app/logs
      - hf_cache:/root/.cache/huggingface
      - ocr_cache:/root/.EasyOCR

volumes:
  app_logs:
  hf_cache:
  ocr_cache: 