version: '3.8'

services:
  docling-inference:
    build: .
    image: docling-inference:latest
    ports:
      - 8877:8080
    environment:
      - DEV_MODE=1
      - AUTH_TOKEN=dev-key
      - NUM_WORKERS=12
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src:ro
      - hf_cache:/root/.cache/huggingface
      - ocr_cache:/root/.EasyOCR
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 16G

volumes:
  hf_cache:
  ocr_cache:
